import { createSlice } from "@reduxjs/toolkit";

export const languageSlice = createSlice({
	name: "language",
	initialState: {
		words: {
			en: {
				set_language: "TÜRKÇE",
				sample: "SAMPLE",
				clear_all: "CLEAR ALL",
				pdf: "PDF",
				live_edit: "LIVE EDIT",
				import: "IMPORT",
				export: "EXPORT",
				primary: "Primary",
				secondary: "Secondary",
				title: "Main Title",
				subtitle: "Subtitle",
				titles: "Titles",
				textLeft: "Text 1",
				textRight: "Text 2",
				color_hint: "* double click the color for the default color",
				add: "ADD",
				clear: "CLEAR",
				personal_information: "Personal Information",
				social: "Social",
				languages: "Languages",
				hobbies: "Hobbies",
				education: "Education",
				experience: "Experience",
				skills: "Skills",
				projects: "Projects",
				courses: "Courses",
				references: "References",
				social_upper: "SOCIAL",
				languages_upper: "LANGUAGES",
				hobbies_upper: "HOBBIES",
				education_upper: "EDUCATION",
				experience_upper: "EXPERIENCE",
				skills_upper: "SKILLS",
				projects_upper: "PROJECTS",
				courses_upper: "COURSES",
				references_upper: "REFERENCES",
				name_surname: "Name Surname",
				form_title: "Title",
				photo: "Photo",
				address: "Address",
				phone_number: "Phone Number",
				email_address: "Email Address",
				about: "About",
				twitter_username: "Twitter Username",
				github_username: "Github Username",
				linkedin_username: "LinkedIn Username",
				personal_website: "Personal Website",
				external_url: "External URL",
				username_or_url: "Username or URL Address",
				select: "Select",
				language: "Language Name",
				native: "Native Language",
				hobby: "Hobby Name",
				school: "School Name",
				subject: "Subject",
				degree: "Degree",
				city: "City",
				from: "From",
				to: "To",
				company: "Company Name",
				position: "Position",
				description: "Description",
				skill: "Skill Name",
				level: "Level",
				project: "Project Name",
				link: "Project Link",
				course: "Course Name",
				reference: "Reference Name",
				reference_title: "Reference Title",
				confirm: "Are you sure all data will be deleted?",
				top: "Top",
				right: "Right",
				bottom: "Bottom",
				left: "Left",
				margin_hint: "* you can set print page margins",
			},
			am: {
				set_language: "አማርኛ",
				sample: "ናሙና",
				clear_all: "ሁሉንም አጽዳ",
				pdf: "PDF",
				live_edit: "ቀጥታ አርትዕ",
				import: "አስገባ",
				export: "አስወጣ",
				primary: "ዋና",
				secondary: "ሁለተኛ",
				title: "ዋና ርዕስ",
				subtitle: "ንኡስ ርዕስ",
				titles: "ርዕሶች",
				textLeft: "ጽሑፍ 1",
				textRight: "ጽሑፍ 2",
				color_hint: "* ለነባሪ ቀለም ቀለሙን ሁለቴ ጠቅ ያድርጉ",
				add: "ጨምር",
				clear: "አጥፋ",
				personal_information: "የግል መረጃ",
				social: "ማህበራዊ",
				languages: "ቋንቋዎች",
				hobbies: "የትርፍ ጊዜ ማሳለፊያዎች",
				education: "ትምህርት",
				experience: "ልምድ",
				skills: "ችሎታዎች",
				projects: "ፕሮጀክቶች",
				courses: "ኮርሶች",
				references: "ማጣቀሻዎች",
				social_upper: "ማህበራዊ",
				languages_upper: "ቋንቋዎች",
				hobbies_upper: "የትርፍ ጊዜ ማሳለፊያዎች",
				education_upper: "ትምህርት",
				experience_upper: "ልምድ",
				skills_upper: "ችሎታዎች",
				projects_upper: "ፕሮጀክቶች",
				courses_upper: "ኮርሶች",
				references_upper: "ማጣቀሻዎች",
				name_surname: "ስም የአያት ስም",
				form_title: "ርዕስ",
				photo: "ፎቶ",
				address: "አድራሻ",
				phone_number: "ስልክ ቁጥር",
				email_address: "ኢሜል አድራሻ",
				about: "ስለ",
				twitter_username: "የትዊተር ተጠቃሚ ስም",
				github_username: "የጊትሃብ ተጠቃሚ ስም",
				linkedin_username: "የሊንክድእን ተጠቃሚ ስም",
				personal_website: "የግል ድር ጣቢያ",
				external_url: "ውጫዊ ድር ጣቢያ",
				username_or_url: "የተጠቃሚ ስም ወይም ድር ጣቢያ አድራሻ",
				select: "ምረጥ",
				language: "የቋንቋ ስም",
				native: "የአፍ መፍቻ ቋንቋ",
				hobby: "የትርፍ ጊዜ ማሳለፊያ ነገር ስም",
				school: "የትምህርት ቤት ስም",
				subject: "ርዕሰ ጉዳይ",
				degree: "ዲግሪ",
				city: "ከተማ",
				from: "ከ",
				to: "እስከ",
				company: "የኩባንያ ስም",
				position: "ቦታ",
				description: "መግለጫ",
				skill: "የችሎታ ስም",
				level: "ደረጃ",
				project: "የፕሮጀክት ስም",
				link: "የፕሮጀክት አገናኝ",
				course: "የኮርስ ስም",
				reference: "የማጣቀሻ ስም",
				reference_title: "የማጣቀሻ ርዕስ",
				confirm: "እርግጠኛ ነዎት ሁሉም ውሂብ ይሰረዛል?",
				top: "ላይ",
				right: "ቀኝ",
				bottom: "ታች",
				left: "ግራ",
				margin_hint: "* የሕትመት ገጽ ህዳጎችን ማዘጋጀት ይችላሉ",
			}
		},
		language: "en",
	},
	reducers: {
		setLanguage: (state, action) => {
			state.language = action.payload;
		},
	},
});

export const { setLanguage } = languageSlice.actions;

export default languageSlice.reducer;
