import "./globals.css";
import Providers from "./Providers";

export const metadata = {
  title: "Fetagn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <body className="bg-white py-3 sm:py-0 dark:bg-gray-800">
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}